export const FETCH_SURVEYS = 'FETCH_SURVEYS'

export const FETCH_SURVEYS_ERROR = 'FETCH_SURVEYS_ERROR'

export const FETCH_SURVEYS_SUCCESS = 'FETCH_SURVEYS_SUCCESS'

export const DELETE_SURVEYS = 'DELETE_SURVEYS'

export const DELETE_SURVEYS_SUCCESS = 'DELETE_SURVEYS_SUCCESS'

export const DELETE_SURVEYS_ERROR = 'DELETE_SURVEYS_ERROR'
